#ifndef _DEFINITIONS_H_
#define _DEFINITIONS_H_

#include "functional"
typedef std::function<void(int newMode)> ModeSelectEvent;
typedef std::function<void(int percentDone)> UpdateEvent;


// BWF Code for inside and outside
#define INSIDE_BWF          86
#define OUTSIDE_BWF         5

#define LED_PIN 17
#define SWITCH_3_PIN 13
#define SWITCH_BOOT_PIN 0

#define LEFT_MOTOR_FORWARD_PWM_PIN 27
#define LEFT_MOTOR_BACKWARDS_PWM_PIN 14
#define LEFT_MOTOR_PWM_CHANNEL_FORWARD 8
#define LEFT_MOTOR_PWM_CHANNEL_BACKWARDS 7
#define LEFT_MOTOR_SENSE_PIN 34

#define RIGHT_MOTOR_FORWARD_PWM_PIN 12
#define RIGHT_MOTOR_BACKWARDS_PWM_PIN 16
#define RIGHT_MOTOR_PWM_CHANNEL_FORWARD 6
#define RIGHT_MOTOR_PWM_CHANNEL_BACKWARDS 5
#define RIGHT_MOTOR_SENSE_PIN 35

#define CUTTER_MOTOR_FORWARD_PWM_PIN 15
#define CUTTER_MOTOR_BACKWARDS_PWM_PIN 5
#define CUTTER_MOTOR_PWM_CHANNEL_FORWARD 4
#define CUTTER_MOTOR_PWM_CHANNEL_BACKWARDS 3
#define CUTTER_MOTOR_SENSE_PIN 32

#define AUX_MOTOR_FORWARD_PWM_PIN 23
#define AUX_MOTOR_BACKWARDS_PWM_PIN 4
#define AUX_MOTOR_PWM_CHANNEL_FORWARD 2
#define AUX_MOTOR_PWM_CHANNEL_BACKWARDS 1
#define AUX_MOTOR_SENSE_PIN 39


#define LOAD_LIMIT_WHEEL 200
#define LOAD_LIMIT_CUTTER 110
#define LOAD_LIMIT_AUX 200

#define LEFT_SENSOR_PIN 26
#define RIGHT_SENSOR_PIN 25

#define BATTERY_SENSOR_PIN 33
#define BATTERY_CHARGE_PIN 36

#define BUMPER_PIN 19

#define FULL_SPEED 255
#define NORMAL_ACCELERATION_TIME 400
#define SHORT_ACCELERATION_TIME 100

#define CUTTER_SPEED 255

#define TILT_ANGLE 60;
#define FLIP_ANGLE 100;

#define OPTION_STEP_TIME 750

//ALTER THESE TOGETHER
#define ANALOG_RESOLUTION 11
#define ANALOG_RESOLUTION_MAX_VALUE 2048

#define ERROR_NOERROR 0
#define ERROR_FLIPPED 1

#endif

